name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  godot:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Godot
        uses: actions/cache@v4
        with:
          path: ~/godot
          key: godot-4.3-stable

      - name: Install Godot
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          unzip Godot_v4.3-stable_linux.x86_64.zip -d ~/godot
          chmod +x ~/godot/Godot_v4.3-stable_linux.x86_64
          
  templates:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Godot Export Templates
        uses: actions/cache@v4
        with:
          path: ~/.local/share/godot/templates/4.3.stable/
          key: godot-templates-4.3

      - name: Install HTML5 export templates
        if: steps.cache-godot-export-templates-cache.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.3.stable/
          unzip Godot_v4.3-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/4.3.stable/

  build:
    runs-on: ubuntu-latest
    needs:
      - templates
      - godot
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Export project to HTML5
        run: |
          ~/godot/Godot_v4.3-stable_linux.x86_64 --export "Web" build/web/

  archive:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: godot-build
          path: build/

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Cache MinIO Client
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/mc
          key: minio-client

      - name: Install MinIO Client
        if: steps.cache-minio-client.outputs.cache-hit != 'true'
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv mc /usr/local/bin/

      - name: Configure MinIO Client
        run: |
          /usr/local/bin/mc alias set myminio ${{ MINIO_HOST }} ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}

      - name: Upload to MinIO
        run: |
          /usr/local/bin/mc cp --recursive build/web/ myminio/ludumdare56/
